config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params

    if @book.save
      flash[:success] = "Saved!"
      redirect_to root_url
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Updated!"
      redirect_to root_url
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted!"
    redirect_to books_url, status: :see_other
  end

  private

    def book_params
      params.require(:book).permit(:name, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<tr>
  <td><%= book.name %></td>
  <td><%= book.author %></td>
  <td><%= link_to "edit_book_#{book.id}", edit_book_path(book) %> | 
      <%= link_to "delete_book_#{book.id}", book, 
                            data: { "turbo-method": :delete,
                                    turbo_confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: @book) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit 'save' %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit book</h2>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @books %>
  </tbody>
</table>

<%= link_to "Add book", new_book_url %>

app/views/books/new.html.erb
<% provide(:button_text, 'save') %>
<h2>New book</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>